/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getArrayType()
 * @model
 * @generated
 */
public interface ArrayType extends MessageType
{
} // ArrayType
