/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Date Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getDateType()
 * @model
 * @generated
 */
public interface DateType extends PropertyType
{
} // DateType
