/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.ExpressionLiteral#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getExpressionLiteral()
 * @model
 * @generated
 */
public interface ExpressionLiteral extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Expression)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getExpressionLiteral_Value()
   * @model containment="true"
   * @generated
   */
  Expression getValue();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.ExpressionLiteral#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Expression value);

} // ExpressionLiteral
