/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends STimeout, SBreakOnNoLock
{
} // Expression
