/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Finally</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.Finally#getFinallyStatements <em>Finally Statements</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getFinally()
 * @model
 * @generated
 */
public interface Finally extends EObject
{
  /**
   * Returns the value of the '<em><b>Finally Statements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Finally Statements</em>' containment reference.
   * @see #setFinallyStatements(TopLevelStatements)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getFinally_FinallyStatements()
   * @model containment="true"
   * @generated
   */
  TopLevelStatements getFinallyStatements();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.Finally#getFinallyStatements <em>Finally Statements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Finally Statements</em>' containment reference.
   * @see #getFinallyStatements()
   * @generated
   */
  void setFinallyStatements(TopLevelStatements value);

} // Finally
