/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For All Identifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.ForAllIdentifier#getOp <em>Op</em>}</li>
 *   <li>{@link com.dexels.navajo.navascript.ForAllIdentifier#getExpression <em>Expression</em>}</li>
 *   <li>{@link com.dexels.navajo.navascript.ForAllIdentifier#getMessagedefinition <em>Messagedefinition</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getForAllIdentifier()
 * @model
 * @generated
 */
public interface ForAllIdentifier extends EObject
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getForAllIdentifier_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.ForAllIdentifier#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getForAllIdentifier_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.ForAllIdentifier#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Messagedefinition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Messagedefinition</em>' attribute.
   * @see #setMessagedefinition(String)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getForAllIdentifier_Messagedefinition()
   * @model
   * @generated
   */
  String getMessagedefinition();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.ForAllIdentifier#getMessagedefinition <em>Messagedefinition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Messagedefinition</em>' attribute.
   * @see #getMessagedefinition()
   * @generated
   */
  void setMessagedefinition(String value);

} // ForAllIdentifier
