/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Key Value Arguments</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.KeyValueArguments#getKeyValueArguments <em>Key Value Arguments</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getKeyValueArguments()
 * @model
 * @generated
 */
public interface KeyValueArguments extends EObject
{
  /**
   * Returns the value of the '<em><b>Key Value Arguments</b></em>' containment reference list.
   * The list contents are of type {@link com.dexels.navajo.navascript.KeyValueArgument}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key Value Arguments</em>' containment reference list.
   * @see com.dexels.navajo.navascript.NavascriptPackage#getKeyValueArguments_KeyValueArguments()
   * @model containment="true"
   * @generated
   */
  EList<KeyValueArgument> getKeyValueArguments();

} // KeyValueArguments
