/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.Loop#getMappable <em>Mappable</em>}</li>
 *   <li>{@link com.dexels.navajo.navascript.Loop#getTml <em>Tml</em>}</li>
 *   <li>{@link com.dexels.navajo.navascript.Loop#getFilter <em>Filter</em>}</li>
 *   <li>{@link com.dexels.navajo.navascript.Loop#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getLoop()
 * @model
 * @generated
 */
public interface Loop extends EObject
{
  /**
   * Returns the value of the '<em><b>Mappable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mappable</em>' containment reference.
   * @see #setMappable(MappableIdentifier)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getLoop_Mappable()
   * @model containment="true"
   * @generated
   */
  MappableIdentifier getMappable();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.Loop#getMappable <em>Mappable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mappable</em>' containment reference.
   * @see #getMappable()
   * @generated
   */
  void setMappable(MappableIdentifier value);

  /**
   * Returns the value of the '<em><b>Tml</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tml</em>' containment reference.
   * @see #setTml(TmlIdentifier)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getLoop_Tml()
   * @model containment="true"
   * @generated
   */
  TmlIdentifier getTml();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.Loop#getTml <em>Tml</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tml</em>' containment reference.
   * @see #getTml()
   * @generated
   */
  void setTml(TmlIdentifier value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' containment reference.
   * @see #setFilter(Expression)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getLoop_Filter()
   * @model containment="true"
   * @generated
   */
  Expression getFilter();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.Loop#getFilter <em>Filter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter</em>' containment reference.
   * @see #getFilter()
   * @generated
   */
  void setFilter(Expression value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link com.dexels.navajo.navascript.InnerBody}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see com.dexels.navajo.navascript.NavascriptPackage#getLoop_Statements()
   * @model containment="true"
   * @generated
   */
  EList<InnerBody> getStatements();

} // Loop
