/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mapped Array Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.MappedArrayMessage#getMessage <em>Message</em>}</li>
 *   <li>{@link com.dexels.navajo.navascript.MappedArrayMessage#getFilter <em>Filter</em>}</li>
 *   <li>{@link com.dexels.navajo.navascript.MappedArrayMessage#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getMappedArrayMessage()
 * @model
 * @generated
 */
public interface MappedArrayMessage extends EObject
{
  /**
   * Returns the value of the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' attribute.
   * @see #setMessage(String)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getMappedArrayMessage_Message()
   * @model
   * @generated
   */
  String getMessage();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.MappedArrayMessage#getMessage <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' attribute.
   * @see #getMessage()
   * @generated
   */
  void setMessage(String value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' containment reference.
   * @see #setFilter(Expression)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getMappedArrayMessage_Filter()
   * @model containment="true"
   * @generated
   */
  Expression getFilter();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.MappedArrayMessage#getFilter <em>Filter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter</em>' containment reference.
   * @see #getFilter()
   * @generated
   */
  void setFilter(Expression value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link com.dexels.navajo.navascript.InnerBody}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see com.dexels.navajo.navascript.NavascriptPackage#getMappedArrayMessage_Statements()
   * @model containment="true"
   * @generated
   */
  EList<InnerBody> getStatements();

} // MappedArrayMessage
