/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mapped Array Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.MappedArrayField#getField <em>Field</em>}</li>
 *   <li>{@link com.dexels.navajo.navascript.MappedArrayField#getFilter <em>Filter</em>}</li>
 *   <li>{@link com.dexels.navajo.navascript.MappedArrayField#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getMappedArrayField()
 * @model
 * @generated
 */
public interface MappedArrayField extends EObject
{
  /**
   * Returns the value of the '<em><b>Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field</em>' attribute.
   * @see #setField(String)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getMappedArrayField_Field()
   * @model
   * @generated
   */
  String getField();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.MappedArrayField#getField <em>Field</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field</em>' attribute.
   * @see #getField()
   * @generated
   */
  void setField(String value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' containment reference.
   * @see #setFilter(Expression)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getMappedArrayField_Filter()
   * @model containment="true"
   * @generated
   */
  Expression getFilter();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.MappedArrayField#getFilter <em>Filter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter</em>' containment reference.
   * @see #getFilter()
   * @generated
   */
  void setFilter(Expression value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link com.dexels.navajo.navascript.InnerBody}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see com.dexels.navajo.navascript.NavascriptPackage#getMappedArrayField_Statements()
   * @model containment="true"
   * @generated
   */
  EList<InnerBody> getStatements();

} // MappedArrayField
