/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message Mode</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getMessageMode()
 * @model
 * @generated
 */
public interface MessageMode extends MessageArgument
{
} // MessageMode
