/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message Array</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.MessageArray#getArrayMessageElements <em>Array Message Elements</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getMessageArray()
 * @model
 * @generated
 */
public interface MessageArray extends EObject
{
  /**
   * Returns the value of the '<em><b>Array Message Elements</b></em>' containment reference list.
   * The list contents are of type {@link com.dexels.navajo.navascript.MessageArrayElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array Message Elements</em>' containment reference list.
   * @see com.dexels.navajo.navascript.NavascriptPackage#getMessageArray_ArrayMessageElements()
   * @model containment="true"
   * @generated
   */
  EList<MessageArrayElement> getArrayMessageElements();

} // MessageArray
