/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Overwrite</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getOverwrite()
 * @model
 * @generated
 */
public interface Overwrite extends MessageMode
{
} // Overwrite
