/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Selection Array</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.SelectionArray#getArrayElements <em>Array Elements</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getSelectionArray()
 * @model
 * @generated
 */
public interface SelectionArray extends EObject
{
  /**
   * Returns the value of the '<em><b>Array Elements</b></em>' containment reference list.
   * The list contents are of type {@link com.dexels.navajo.navascript.SelectionArrayElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array Elements</em>' containment reference list.
   * @see com.dexels.navajo.navascript.NavascriptPackage#getSelectionArray_ArrayElements()
   * @model containment="true"
   * @generated
   */
  EList<SelectionArrayElement> getArrayElements();

} // SelectionArray
