/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Synchronized</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.Synchronized#getArguments <em>Arguments</em>}</li>
 *   <li>{@link com.dexels.navajo.navascript.Synchronized#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getSynchronized()
 * @model
 * @generated
 */
public interface Synchronized extends EObject
{
  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference.
   * @see #setArguments(SynchronizedArguments)
   * @see com.dexels.navajo.navascript.NavascriptPackage#getSynchronized_Arguments()
   * @model containment="true"
   * @generated
   */
  SynchronizedArguments getArguments();

  /**
   * Sets the value of the '{@link com.dexels.navajo.navascript.Synchronized#getArguments <em>Arguments</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arguments</em>' containment reference.
   * @see #getArguments()
   * @generated
   */
  void setArguments(SynchronizedArguments value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link com.dexels.navajo.navascript.TopLevelStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see com.dexels.navajo.navascript.NavascriptPackage#getSynchronized_Statements()
   * @model containment="true"
   * @generated
   */
  EList<TopLevelStatement> getStatements();

} // Synchronized
