/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Array Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.VarArrayElement#getVarElements <em>Var Elements</em>}</li>
 * </ul>
 *
 * @see com.dexels.navajo.navascript.NavascriptPackage#getVarArrayElement()
 * @model
 * @generated
 */
public interface VarArrayElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Var Elements</b></em>' containment reference list.
   * The list contents are of type {@link com.dexels.navajo.navascript.VarElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Elements</em>' containment reference list.
   * @see com.dexels.navajo.navascript.NavascriptPackage#getVarArrayElement_VarElements()
   * @model containment="true"
   * @generated
   */
  EList<VarElement> getVarElements();

} // VarArrayElement
