/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript.impl;

import com.dexels.navajo.navascript.ClockTimeType;
import com.dexels.navajo.navascript.NavascriptPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Clock Time Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ClockTimeTypeImpl extends PropertyTypeImpl implements ClockTimeType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClockTimeTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NavascriptPackage.Literals.CLOCK_TIME_TYPE;
  }

} //ClockTimeTypeImpl
