/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript.impl;

import com.dexels.navajo.navascript.Finally;
import com.dexels.navajo.navascript.NavascriptPackage;
import com.dexels.navajo.navascript.TopLevelStatements;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Finally</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.impl.FinallyImpl#getFinallyStatements <em>Finally Statements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FinallyImpl extends MinimalEObjectImpl.Container implements Finally
{
  /**
   * The cached value of the '{@link #getFinallyStatements() <em>Finally Statements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFinallyStatements()
   * @generated
   * @ordered
   */
  protected TopLevelStatements finallyStatements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FinallyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NavascriptPackage.Literals.FINALLY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TopLevelStatements getFinallyStatements()
  {
    return finallyStatements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFinallyStatements(TopLevelStatements newFinallyStatements, NotificationChain msgs)
  {
    TopLevelStatements oldFinallyStatements = finallyStatements;
    finallyStatements = newFinallyStatements;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, NavascriptPackage.FINALLY__FINALLY_STATEMENTS, oldFinallyStatements, newFinallyStatements);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFinallyStatements(TopLevelStatements newFinallyStatements)
  {
    if (newFinallyStatements != finallyStatements)
    {
      NotificationChain msgs = null;
      if (finallyStatements != null)
        msgs = ((InternalEObject)finallyStatements).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - NavascriptPackage.FINALLY__FINALLY_STATEMENTS, null, msgs);
      if (newFinallyStatements != null)
        msgs = ((InternalEObject)newFinallyStatements).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - NavascriptPackage.FINALLY__FINALLY_STATEMENTS, null, msgs);
      msgs = basicSetFinallyStatements(newFinallyStatements, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, NavascriptPackage.FINALLY__FINALLY_STATEMENTS, newFinallyStatements, newFinallyStatements));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case NavascriptPackage.FINALLY__FINALLY_STATEMENTS:
        return basicSetFinallyStatements(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case NavascriptPackage.FINALLY__FINALLY_STATEMENTS:
        return getFinallyStatements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case NavascriptPackage.FINALLY__FINALLY_STATEMENTS:
        setFinallyStatements((TopLevelStatements)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case NavascriptPackage.FINALLY__FINALLY_STATEMENTS:
        setFinallyStatements((TopLevelStatements)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case NavascriptPackage.FINALLY__FINALLY_STATEMENTS:
        return finallyStatements != null;
    }
    return super.eIsSet(featureID);
  }

} //FinallyImpl
