/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript.impl;

import com.dexels.navajo.navascript.Expression;
import com.dexels.navajo.navascript.ForAllIdentifier;
import com.dexels.navajo.navascript.NavascriptPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>For All Identifier</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.impl.ForAllIdentifierImpl#getOp <em>Op</em>}</li>
 *   <li>{@link com.dexels.navajo.navascript.impl.ForAllIdentifierImpl#getExpression <em>Expression</em>}</li>
 *   <li>{@link com.dexels.navajo.navascript.impl.ForAllIdentifierImpl#getMessagedefinition <em>Messagedefinition</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ForAllIdentifierImpl extends MinimalEObjectImpl.Container implements ForAllIdentifier
{
  /**
   * The default value of the '{@link #getOp() <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOp()
   * @generated
   * @ordered
   */
  protected static final String OP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOp() <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOp()
   * @generated
   * @ordered
   */
  protected String op = OP_EDEFAULT;

  /**
   * The cached value of the '{@link #getExpression() <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpression()
   * @generated
   * @ordered
   */
  protected Expression expression;

  /**
   * The default value of the '{@link #getMessagedefinition() <em>Messagedefinition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMessagedefinition()
   * @generated
   * @ordered
   */
  protected static final String MESSAGEDEFINITION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMessagedefinition() <em>Messagedefinition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMessagedefinition()
   * @generated
   * @ordered
   */
  protected String messagedefinition = MESSAGEDEFINITION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ForAllIdentifierImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NavascriptPackage.Literals.FOR_ALL_IDENTIFIER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOp()
  {
    return op;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOp(String newOp)
  {
    String oldOp = op;
    op = newOp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, NavascriptPackage.FOR_ALL_IDENTIFIER__OP, oldOp, op));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getExpression()
  {
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpression(Expression newExpression, NotificationChain msgs)
  {
    Expression oldExpression = expression;
    expression = newExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, NavascriptPackage.FOR_ALL_IDENTIFIER__EXPRESSION, oldExpression, newExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExpression(Expression newExpression)
  {
    if (newExpression != expression)
    {
      NotificationChain msgs = null;
      if (expression != null)
        msgs = ((InternalEObject)expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - NavascriptPackage.FOR_ALL_IDENTIFIER__EXPRESSION, null, msgs);
      if (newExpression != null)
        msgs = ((InternalEObject)newExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - NavascriptPackage.FOR_ALL_IDENTIFIER__EXPRESSION, null, msgs);
      msgs = basicSetExpression(newExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, NavascriptPackage.FOR_ALL_IDENTIFIER__EXPRESSION, newExpression, newExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMessagedefinition()
  {
    return messagedefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMessagedefinition(String newMessagedefinition)
  {
    String oldMessagedefinition = messagedefinition;
    messagedefinition = newMessagedefinition;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, NavascriptPackage.FOR_ALL_IDENTIFIER__MESSAGEDEFINITION, oldMessagedefinition, messagedefinition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case NavascriptPackage.FOR_ALL_IDENTIFIER__EXPRESSION:
        return basicSetExpression(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case NavascriptPackage.FOR_ALL_IDENTIFIER__OP:
        return getOp();
      case NavascriptPackage.FOR_ALL_IDENTIFIER__EXPRESSION:
        return getExpression();
      case NavascriptPackage.FOR_ALL_IDENTIFIER__MESSAGEDEFINITION:
        return getMessagedefinition();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case NavascriptPackage.FOR_ALL_IDENTIFIER__OP:
        setOp((String)newValue);
        return;
      case NavascriptPackage.FOR_ALL_IDENTIFIER__EXPRESSION:
        setExpression((Expression)newValue);
        return;
      case NavascriptPackage.FOR_ALL_IDENTIFIER__MESSAGEDEFINITION:
        setMessagedefinition((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case NavascriptPackage.FOR_ALL_IDENTIFIER__OP:
        setOp(OP_EDEFAULT);
        return;
      case NavascriptPackage.FOR_ALL_IDENTIFIER__EXPRESSION:
        setExpression((Expression)null);
        return;
      case NavascriptPackage.FOR_ALL_IDENTIFIER__MESSAGEDEFINITION:
        setMessagedefinition(MESSAGEDEFINITION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case NavascriptPackage.FOR_ALL_IDENTIFIER__OP:
        return OP_EDEFAULT == null ? op != null : !OP_EDEFAULT.equals(op);
      case NavascriptPackage.FOR_ALL_IDENTIFIER__EXPRESSION:
        return expression != null;
      case NavascriptPackage.FOR_ALL_IDENTIFIER__MESSAGEDEFINITION:
        return MESSAGEDEFINITION_EDEFAULT == null ? messagedefinition != null : !MESSAGEDEFINITION_EDEFAULT.equals(messagedefinition);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (op: ");
    result.append(op);
    result.append(", messagedefinition: ");
    result.append(messagedefinition);
    result.append(')');
    return result.toString();
  }

} //ForAllIdentifierImpl
