/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript.impl;

import com.dexels.navajo.navascript.MessageMode;
import com.dexels.navajo.navascript.NavascriptPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Message Mode</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MessageModeImpl extends MessageArgumentImpl implements MessageMode
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MessageModeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NavascriptPackage.Literals.MESSAGE_MODE;
  }

} //MessageModeImpl
