/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript.impl;

import com.dexels.navajo.navascript.NavascriptPackage;
import com.dexels.navajo.navascript.SBreakOnNoLock;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SBreak On No Lock</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SBreakOnNoLockImpl extends SynchronizedArgumentImpl implements SBreakOnNoLock
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SBreakOnNoLockImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NavascriptPackage.Literals.SBREAK_ON_NO_LOCK;
  }

} //SBreakOnNoLockImpl
