/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.navascript.impl;

import com.dexels.navajo.navascript.InnerBody;
import com.dexels.navajo.navascript.NavascriptPackage;
import com.dexels.navajo.navascript.SelectionArrayElement;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Selection Array Element</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.dexels.navajo.navascript.impl.SelectionArrayElementImpl#getInnerBody <em>Inner Body</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SelectionArrayElementImpl extends MinimalEObjectImpl.Container implements SelectionArrayElement
{
  /**
   * The cached value of the '{@link #getInnerBody() <em>Inner Body</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInnerBody()
   * @generated
   * @ordered
   */
  protected EList<InnerBody> innerBody;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SelectionArrayElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NavascriptPackage.Literals.SELECTION_ARRAY_ELEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<InnerBody> getInnerBody()
  {
    if (innerBody == null)
    {
      innerBody = new EObjectContainmentEList<InnerBody>(InnerBody.class, this, NavascriptPackage.SELECTION_ARRAY_ELEMENT__INNER_BODY);
    }
    return innerBody;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case NavascriptPackage.SELECTION_ARRAY_ELEMENT__INNER_BODY:
        return ((InternalEList<?>)getInnerBody()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case NavascriptPackage.SELECTION_ARRAY_ELEMENT__INNER_BODY:
        return getInnerBody();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case NavascriptPackage.SELECTION_ARRAY_ELEMENT__INNER_BODY:
        getInnerBody().clear();
        getInnerBody().addAll((Collection<? extends InnerBody>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case NavascriptPackage.SELECTION_ARRAY_ELEMENT__INNER_BODY:
        getInnerBody().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case NavascriptPackage.SELECTION_ARRAY_ELEMENT__INNER_BODY:
        return innerBody != null && !innerBody.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //SelectionArrayElementImpl
