/**
 * generated by Xtext 2.24.0
 */
package com.dexels.navajo.tests;

import com.dexels.navajo.navascript.Navascript;
import com.dexels.navajo.tests.NavascriptInjectorProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

/* @ExtendWith(/* name is null */)
@InjectWith(NavascriptInjectorProvider.class) */@SuppressWarnings("all")
public class NavascriptParsingTest {
  /* @Inject
   */private /* ParseHelper<Navascript> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field NavascriptParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
